# Generated by Django 4.0.6 on 2022-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='chapter',
            new_name='exam_chapter',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='course',
            new_name='exam_course',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='duration',
            new_name='exam_duration',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='exam_name',
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
