# Generated by Django 4.0.6 on 2022-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_api', '0003_remove_exam_uploadquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
