# Generated by Django 4.0.6 on 2022-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(default=None, upload_to='Blogs')),
                ('author', models.CharField(max_length=30)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
