# Generated by Django 4.0.6 on 2022-08-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_blogcomment'),
        ('blog_api', '0003_comment_blog'),
    ]

    operations = [
    ]
