# Generated by Django 4.0.2 on 2022-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0004_alter_video_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
