# Generated by Django 4.0.2 on 2022-07-08 11:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(default=None, upload_to='')),
                ('author', models.CharField(max_length=30)),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Math', 'Math')], default='physics', max_length=20)),
                ('publish_date', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
