# Generated by Django 4.0.2 on 2022-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subject',
        ),
        migrations.AddField(
            model_name='blog',
            name='subject',
            field=models.ManyToManyField(to='Blog.Subject'),
        ),
    ]
