# Generated by Django 4.0.2 on 2022-07-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_subject_remove_blog_subject_blog_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
